<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://test" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://test" xmlns:intf="http://test" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://test" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="squire">
    <complexType>
     <sequence>
      <element name="a" type="xsd:int"/>
     </sequence>
    </complexType>
   </element>
   <element name="squireResponse">
    <complexType>
     <sequence>
      <element name="squireReturn" type="xsd:int"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="squireRequest">

      <wsdl:part element="impl:squire" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="squireResponse">

      <wsdl:part element="impl:squireResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="AndroidWebService">

      <wsdl:operation name="squire">

         <wsdl:input message="impl:squireRequest" name="squireRequest">

       </wsdl:input>

         <wsdl:output message="impl:squireResponse" name="squireResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="AndroidWebServiceSoapBinding" type="impl:AndroidWebService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="squire">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="squireRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="squireResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="AndroidWebServiceService">

      <wsdl:port binding="impl:AndroidWebServiceSoapBinding" name="AndroidWebService">

         <wsdlsoap:address location="http://localhost:8080/AndroidSOAPExample/services/AndroidWebService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
